import { faGithub } from '@fortawesome/free-brands-svg-icons';
import {
    faEllipsisH,
    faTimes,
    faUser,
    faUsers,
    faBell,
    faPlus,
    faColumns,
    faQuestionCircle,
    faSignOutAlt,
    faCog,
    faChevronDown,
    faChevronUp,
    faChevronRight,
    faListAlt,
} from '@fortawesome/free-solid-svg-icons';

export default [
    faEllipsisH,
    faGithub,
    faTimes,
    faUser,
    faUsers,
    faBell,
    faPlus,
    faColumns,
    faQuestionCircle,
    faSignOutAlt,
    faCog,
    faChevronDown,
    faChevronUp,
    faChevronRight,
    faListAlt,
];
